// Generated by scripts/sync-model-catalog.py. Do not edit.
export const MODEL_CATALOG = {
  "version": 1,
  "catalog_sha256": "02ac64f6bf94ca8c77748a95f3a81341d56dbea5f22837e2706a4bea6610a45d",
  "providers": {
    "google": {
      "default": "gemini-3.1-flash-lite",
      "models": [
        {
          "id": "gemini-3.1-flash-lite",
          "label": "Gemini 3.1 Flash Lite",
          "contextWindow": 1000000,
          "inputCostPerMtok": 0.25,
          "outputCostPerMtok": 1.5,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "thinkingLevel",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": false,
            "notes": "Response pricing = output tokens + thinking tokens."
          }
        },
        {
          "id": "gemini-3.5-flash",
          "label": "Gemini 3.5 Flash",
          "contextWindow": 1048576,
          "inputCostPerMtok": 1.5,
          "outputCostPerMtok": 9.0,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "thinkingLevel",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": false,
            "notes": "Response pricing = output tokens + thinking tokens."
          }
        },
        {
          "id": "gemini-3.1-pro-preview",
          "label": "Gemini 3.1 Pro Preview",
          "contextWindow": 1000000,
          "inputCostPerMtok": 2.0,
          "outputCostPerMtok": 12.0,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "thinkingLevel",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "high",
            "supports_dynamic": false,
            "can_disable": false,
            "notes": "Response pricing = output tokens + thinking tokens."
          }
        },
        {
          "id": "gemini-3.8-flash",
          "label": "Gemini 3.8 Flash",
          "contextWindow": 1048576,
          "inputCostPerMtok": 0.75,
          "outputCostPerMtok": 3.75,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "thinkingLevel",
            "levels": [
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": false,
            "notes": "Response pricing = output tokens + thinking tokens."
          }
        }
      ]
    },
    "openai": {
      "default": "gpt-4o-mini",
      "models": [
        {
          "id": "gpt-4o-mini",
          "label": "gpt-4o-mini",
          "contextWindow": 128000,
          "inputCostPerMtok": 0.15,
          "outputCostPerMtok": 0.6,
          "thinking": {
            "supported": false,
            "mode": "none"
          }
        },
        {
          "id": "gpt-4o",
          "label": "gpt-4o",
          "contextWindow": 128000,
          "inputCostPerMtok": 2.5,
          "outputCostPerMtok": 10.0,
          "thinking": {
            "supported": false,
            "mode": "none"
          }
        },
        {
          "id": "gpt-5.5",
          "label": "gpt-5.5",
          "contextWindow": 1000000,
          "inputCostPerMtok": 5.0,
          "outputCostPerMtok": 30.0,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "reasoning.effort",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Valid effort values are model-dependent; newer models also accept 'none' and 'xhigh'. Reasoning tokens are billed as output tokens."
          }
        },
        {
          "id": "gpt-5.4",
          "label": "gpt-5.4",
          "contextWindow": 1050000,
          "inputCostPerMtok": 2.5,
          "outputCostPerMtok": 15.0,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "reasoning.effort",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Valid effort values are model-dependent; newer models also accept 'none' and 'xhigh'. Reasoning tokens are billed as output tokens."
          }
        },
        {
          "id": "gpt-5.4-mini",
          "label": "gpt-5.4-mini",
          "contextWindow": 400000,
          "inputCostPerMtok": 0.75,
          "outputCostPerMtok": 4.5,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "reasoning.effort",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Valid effort values are model-dependent; newer models also accept 'none' and 'xhigh'. Reasoning tokens are billed as output tokens."
          }
        },
        {
          "id": "gpt-5.1",
          "label": "gpt-5.1",
          "contextWindow": 400000,
          "inputCostPerMtok": 1.25,
          "outputCostPerMtok": 10.0,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "reasoning.effort",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Valid effort values are model-dependent; newer models also accept 'none' and 'xhigh'. Reasoning tokens are billed as output tokens."
          }
        },
        {
          "id": "gpt-5-mini",
          "label": "gpt-5-mini",
          "contextWindow": 400000,
          "inputCostPerMtok": 0.25,
          "outputCostPerMtok": 2.0,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "reasoning.effort",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Valid effort values are model-dependent; newer models also accept 'none' and 'xhigh'. Reasoning tokens are billed as output tokens."
          }
        },
        {
          "id": "gpt-5-nano",
          "label": "gpt-5-nano",
          "contextWindow": 400000,
          "inputCostPerMtok": 0.05,
          "outputCostPerMtok": 0.4,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "reasoning.effort",
            "levels": [
              "minimal",
              "low",
              "medium",
              "high"
            ],
            "default_level": "medium",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Valid effort values are model-dependent; newer models also accept 'none' and 'xhigh'. Reasoning tokens are billed as output tokens."
          }
        }
      ]
    },
    "anthropic": {
      "default": "claude-haiku-4-5-20251001",
      "models": [
        {
          "id": "claude-haiku-4-5-20251001",
          "label": "Claude Haiku 4.5",
          "contextWindow": 200000,
          "inputCostPerMtok": 1.0,
          "outputCostPerMtok": 5.0,
          "thinking": {
            "supported": true,
            "mode": "token_budget",
            "parameter": "thinking.budget_tokens",
            "min_budget": 1024,
            "max_budget": 64000,
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Manual extended thinking only (thinking={type:'enabled',budget_tokens}); thinking={type:'adaptive'} returns a 400 on this model. budget_tokens must be less than max_tokens (64k output ceiling). No interleaved thinking — the interleaved-thinking-2025-05-14 beta header is accepted but ignored.",
            "sampling_params_allowed": {
              "temperature": {
                "status": "forbidden",
                "when": "thinking_enabled"
              },
              "top_k": {
                "status": "forbidden",
                "when": "thinking_enabled"
              },
              "top_p": {
                "status": "range",
                "when": "thinking_enabled",
                "min": 0.95,
                "max": 1.0
              }
            }
          }
        },
        {
          "id": "claude-sonnet-4-6",
          "label": "Claude Sonnet 4.6",
          "contextWindow": 1000000,
          "inputCostPerMtok": 3.0,
          "outputCostPerMtok": 15.0,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "output_config.effort",
            "levels": [
              "low",
              "medium",
              "high",
              "max"
            ],
            "default_level": "high",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Requires thinking={type:'adaptive'}. effort set via output_config.effort. Legacy budget_tokens deprecated. Manual-mode interleaved thinking via interleaved-thinking-2025-05-14 beta header.",
            "sampling_params_allowed": {
              "temperature": {
                "status": "forbidden",
                "when": "thinking_enabled"
              },
              "top_k": {
                "status": "forbidden",
                "when": "thinking_enabled"
              },
              "top_p": {
                "status": "range",
                "when": "thinking_enabled",
                "min": 0.95,
                "max": 1.0
              }
            }
          }
        },
        {
          "id": "claude-opus-4-8",
          "label": "Claude Opus 4.8",
          "contextWindow": 1000000,
          "inputCostPerMtok": 5.0,
          "outputCostPerMtok": 25.0,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "output_config.effort",
            "levels": [
              "low",
              "medium",
              "high",
              "xhigh",
              "max"
            ],
            "default_level": "high",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Requires thinking={type:'adaptive'}. effort set via output_config.effort. Adaptive is the only mode; manual budget_tokens is rejected (400). display defaults to 'omitted'.",
            "sampling_params_allowed": {
              "temperature": {
                "status": "default_only",
                "when": "always"
              },
              "top_p": {
                "status": "default_only",
                "when": "always"
              },
              "top_k": {
                "status": "default_only",
                "when": "always"
              }
            }
          }
        }
      ]
    },
    "deepseek": {
      "default": "deepseek-flash",
      "models": [
        {
          "id": "deepseek-flash",
          "label": "DeepSeek V4.1 Flash",
          "contextWindow": 1000000,
          "inputCostPerMtok": 0.3,
          "outputCostPerMtok": 1.2,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "reasoning_effort",
            "levels": [
              "low",
              "high",
              "max"
            ],
            "default_level": "high",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Thinking toggle defaults to enabled; disable via thinking={type:'disabled'} (Anthropic/Responses format: effort 'none'). Effort compat: minimal->low, medium/xhigh->high, ultra->max. Complex agent requests (Claude Code, OpenCode) auto-set max. Anthropic-format equivalent: output_config.effort. Chain-of-thought returned in reasoning_content."
          }
        },
        {
          "id": "deepseek-v4-pro",
          "label": "DeepSeek V4 Pro",
          "contextWindow": 1000000,
          "inputCostPerMtok": 1.32,
          "outputCostPerMtok": 3.96,
          "thinking": {
            "supported": true,
            "mode": "effort_levels",
            "parameter": "reasoning_effort",
            "levels": [
              "low",
              "high",
              "max"
            ],
            "default_level": "high",
            "supports_dynamic": false,
            "can_disable": true,
            "notes": "Thinking toggle defaults to enabled; disable via thinking={type:'disabled'} (Anthropic/Responses format: effort 'none'). Effort compat: minimal->low, medium/xhigh->high, ultra->max. Complex agent requests (Claude Code, OpenCode) auto-set max. Anthropic-format equivalent: output_config.effort. Chain-of-thought returned in reasoning_content."
          }
        }
      ]
    }
  }
} as const;
