import React from 'react';
import { LabDescriptor } from '../../catalog/types';
import { EMBEDDINGS_CONTENT, TFIDF_CONTENT, NGRAM_CONTENT, NER_CONTENT, SEARCH_CONTENT, CLASSIFY_CONTENT } from './content';

export const ACCENT = '#14b8a6';

export const NLP_LABS: LabDescriptor[] = [
  {
    id: 'word-embeddings',
    category: 'nlp',
    title: 'Word Embeddings & Analogies',
    subtitle: 'vec(b) − vec(a) + vec(c) ≈ ?  ·  cosine similarity',
    blurb: 'Watch king − man + woman land near queen: semantic relations are roughly constant directions in a vector space. 3CosAdd analogies and cosine nearest neighbours in a hand-built 29-D word table, mapped to 2-D by PCA.',
    icon: 'M5 12h4l2-7 3 14 2-7h4M5 19h14',
    accent: ACCENT,
    codeFile: 'word_embeddings.py',
    content: EMBEDDINGS_CONTENT,
    component: React.lazy(() => import('./WordEmbeddings')),
  },
  {
    id: 'tfidf',
    category: 'nlp',
    title: 'TF-IDF & Document Similarity',
    subtitle: 'tf·idf,  idf = ln(N/df)  ·  cosine similarity',
    blurb: 'Turn documents into weighted bag-of-words vectors: TF-IDF boosts rare terms and zeroes "the". Compare every pair by cosine and toggle stop words, sublinear tf and smoothed idf — the classical search baseline.',
    icon: 'M5 4h14v4H5zM5 11h14M5 15h10M5 19h14',
    accent: ACCENT,
    codeFile: 'tfidf.py',
    content: TFIDF_CONTENT,
    component: React.lazy(() => import('./TfIdf')),
  },
  {
    id: 'ngram-lm',
    category: 'nlp',
    title: 'N-gram Language Model',
    subtitle: 'P(wₜ | context) = (count+k)/(total+k·V)  ·  perplexity',
    blurb: 'Build a bigram/trigram model from counts, smooth away the zero-probability trap with add-k, find the k that minimises held-out perplexity, and sample new sentences token by token.',
    icon: 'M4 17l5-10 4 7 3-4 4 7M4 20h16',
    accent: ACCENT,
    codeFile: 'ngram_lm.py',
    content: NGRAM_CONTENT,
    component: React.lazy(() => import('./NgramLM')),
  },
  {
    id: 'ner',
    category: 'nlp',
    title: 'Named Entity Recognition',
    subtitle: 'Viterbi over BIO tags: argmax Σ emission + transition',
    blurb: 'Tag every token with BIO tags for PER / LOC / ORG. Gazetteer, word-shape and context features score each tag; Viterbi finds the best whole-sentence labelling and repairs what per-token guesses get wrong.',
    icon: 'M4 7h4v4H4zM10 7h4v4h-4zM16 7h4v4h-4zM4 15h16',
    accent: ACCENT,
    codeFile: 'ner_viterbi.py',
    content: NER_CONTENT,
    component: React.lazy(() => import('./Ner')),
  },
  {
    id: 'semantic-search',
    category: 'nlp',
    title: 'Semantic Search & RAG',
    subtitle: 'score(d) = cos(q, d)  ·  top-k retrieval',
    blurb: 'Embed a query and a document set from their words, rank by cosine, and retrieve the top-k by meaning where keyword TF-IDF scores zero — the retrieval half of RAG.',
    icon: 'M11 4a7 7 0 1 0 0 14 7 7 0 0 0 0-14zM21 21l-5-5',
    accent: ACCENT,
    codeFile: 'semantic_search.py',
    content: SEARCH_CONTENT,
    component: React.lazy(() => import('./SemanticSearch')),
  },
  {
    id: 'text-classification',
    category: 'nlp',
    title: 'Text Classification',
    subtitle: 'p = σ(w·x + b)  ·  embeddings → decision boundary',
    blurb: 'Embed short reviews from their words, fit a regularised logistic boundary by gradient descent, and classify held-out reviews — the embed-then-separate recipe behind every fine-tuned text classifier.',
    icon: 'M4 12h16M12 4v16M7 7l10 10',
    accent: ACCENT,
    codeFile: 'text_classification.py',
    content: CLASSIFY_CONTENT,
    component: React.lazy(() => import('./TextClassification')),
  },
];
