#!/usr/bin/env python3
"""App-owned offline catalogue curator. Policy changes require code review."""
import argparse
import hashlib
import json
import math
from pathlib import Path


def curate(raw, policy):
    catalog = json.loads(raw)
    if catalog.get('version') != 1:
        raise ValueError('Unsupported catalogue schema')
    result = {'version': 1, 'catalog_sha256': hashlib.sha256(raw).hexdigest(), 'providers': {}}
    for name, rule in policy['providers'].items():
        available = catalog['providers'][rule['source']]
        by_id = {m['model_id']: m for m in available}
        if len(by_id) != len(available):
            raise ValueError('Duplicate model IDs')
        models = []
        for model_id in rule['models']:
            if model_id not in by_id:
                raise ValueError(f'{name}: approved model {model_id} disappeared; review its replacement')
            m = by_id[model_id]
            if m.get('model_type') != 'text' or m.get('deprecated') or m.get('status') in ('deprecated', 'retired'):
                raise ValueError(f'{model_id}: no longer an active text model')
            for field in ('input_cost_per_mtok', 'output_cost_per_mtok'):
                value = m.get(field)
                if type(value) not in (int, float) or not math.isfinite(value) or value < 0:
                    raise ValueError(f'{model_id}: missing/invalid price')
                if field in rule.get('cost_ceiling', {}) and value > rule['cost_ceiling'][field]:
                    raise ValueError(f'{model_id}: exceeds application cost ceiling')
            thinking = m.get('thinking', {'supported': False, 'mode': 'none'})
            if thinking.get('mode') not in rule['thinking_modes']:
                raise ValueError(f'{model_id}: unsupported thinking mode')
            if thinking.get('mode') != 'none' and thinking.get('parameter') not in rule['thinking_parameters']:
                raise ValueError(f'{model_id}: unsupported thinking parameter')
            if thinking.get('mode') == 'effort_levels':
                levels = thinking.get('levels', [])
                if not levels or not set(levels) <= {'none','minimal','low','medium','high','xhigh','max','ultra','instant'}:
                    raise ValueError(f'{model_id}: unknown effort levels')
                if rule.get('required_level') and rule['required_level'] not in levels:
                    raise ValueError(f'{model_id}: required effort no longer supported')
            models.append({
                'id': model_id, 'label': m['display_name'],
                'contextWindow': m.get('context_window'),
                'inputCostPerMtok': m['input_cost_per_mtok'],
                'outputCostPerMtok': m['output_cost_per_mtok'],
                'thinking': thinking,
            })
        if rule['default'] not in rule['models'] or not models:
            raise ValueError(f'{name}: default must be approved')
        result['providers'][name] = {'default': rule['default'], 'models': models}
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--catalog', required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    policy = json.loads((root / 'model-catalog.policy.json').read_text())
    result = curate(Path(args.catalog).read_bytes(), policy)
    output = root / policy['output']
    text = json.dumps(result, indent=2, ensure_ascii=False) + '\n'
    if output.suffix == '.ts':
        text = '// Generated by scripts/sync-model-catalog.py. Do not edit.\nexport const MODEL_CATALOG = ' + text.rstrip() + ' as const;\n'
    elif output.suffix == '.js':
        text = '// Generated by scripts/sync-model-catalog.py. Do not edit.\nexport const MODEL_CATALOG = ' + text.rstrip() + ';\n'
    if args.check:
        if not output.exists() or output.read_text() != text:
            raise ValueError('Generated catalogue is stale')
    else:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(text)
    print(f'{output.relative_to(root)}: {sum(len(p["models"]) for p in result["providers"].values())} approved models')


if __name__ == '__main__':
    main()
